"""
Meeting service (ABF-156).

The platform's side of a scheduled meeting: who may schedule one and for
which cell, what gets written down when one is scheduled, and which meetings
a given member is allowed to see. Talking to Google is
google_meet_service.py's job — nothing in this file makes an HTTP call.

The split matters at exactly one point: the event is created at Google
*before* the transaction that records it, because an event we failed to
create must not leave a meeting row pointing at a join link that does not
exist. The reverse failure — recorded at Google, not recorded here — is
recoverable, and create_meeting() recovers from it.
"""

import logging
from datetime import UTC, datetime, timedelta

from fastapi import HTTPException
from sqlalchemy import and_, or_
from sqlalchemy.orm import Session, joinedload

from app.core.config import settings
from app.core.constants import (
    AuditAction,
    GroupVisibility,
    PostStatus,
    PostType,
    SectorVisibility,
    UserRole,
)
from app.core.i18n import translate
from app.models.forum import ForumPost
from app.models.meeting import Meeting
from app.models.user import User
from app.schemas.meeting import MeetingCreate
from app.services import google_meet_service
from app.services.audit_service import build_entry

logger = logging.getLogger(__name__)

#: How far back get_visible_meetings() looks before deciding, per row, whether
#: a meeting is over. A prefilter, not the rule: the rule is
#: `scheduled_at + duration_minutes >= now`, and expressing that arithmetic in
#: SQL means writing it twice, once per dialect (SQLite and PostgreSQL date
#: arithmetic do not share a syntax). One day back bounds what the prefilter
#: can return to a handful of rows, which Python then filters exactly.
_LOOKBACK = timedelta(days=1)


def _utcnow() -> datetime:
    """Naive UTC, matching how every timestamp in this project is stored."""
    return datetime.now(UTC).replace(tzinfo=None)


def _may_schedule_for(
    professional: User,
    group_visibility: GroupVisibility,
    sector_visibility: SectorVisibility,
) -> bool:
    """
    Whether this professional's assignment covers the requested cell.

    professional_groups / professional_sectors are the same JSON lists that
    decide which professionals a member sees in the catalogue
    (user_service._visible_to_user()), read here in the other direction: a
    professional may convene the members who can already reach her, and
    nobody else. "all" in a list is the wildcard it is everywhere else.
    """
    groups = professional.professional_groups or []
    sectors = professional.professional_sectors or []
    group_match = "all" in groups or group_visibility.value in groups
    sector_match = "all" in sectors or sector_visibility.value in sectors
    return group_match and sector_match


def create_meeting(db: Session, data: MeetingCreate, professional: User) -> Meeting:
    """
    Schedule a meeting and publish its announcement.

    The caller's role is already PROFESSIONAL — require_role does that — so
    what is left here is the part of "may she do this" that depends on the
    data: is she still an active professional, and is this cell hers.
    """
    if not professional.is_active_professional:
        raise HTTPException(
            status_code=403, detail=translate("meetings.inactive_professional")
        )

    if not _may_schedule_for(
        professional, data.group_visibility, data.sector_visibility
    ):
        raise HTTPException(
            status_code=403, detail=translate("meetings.cell_forbidden")
        )

    duration_minutes = settings.MEETING_DEFAULT_DURATION_MINUTES
    meet_link, calendar_event_id = google_meet_service.create_meeting(
        db,
        professional,
        title=data.title,
        scheduled_at=data.scheduled_at,
        duration_minutes=duration_minutes,
    )

    meeting = Meeting(
        creator_id=professional.id,
        title=data.title,
        scheduled_at=data.scheduled_at,
        duration_minutes=duration_minutes,
        meet_link=meet_link,
        calendar_event_id=calendar_event_id,
        group_visibility=data.group_visibility,
        sector_visibility=data.sector_visibility,
    )

    try:
        db.add(meeting)
        # Flushed, not just added: the id is generated by the model's Python
        # default, which does not run until the INSERT is emitted — and the
        # audit entry below has to name it. Still one transaction; the commit
        # is at the end.
        db.flush()
        # The announcement. Its body is the title: what a member actually
        # reads off this post — when it starts, where to join — travels in
        # structured fields on the meeting, and a sentence assembled here
        # would be a second copy of them that the client cannot format or
        # translate.
        db.add(
            ForumPost(
                author_id=professional.id,
                title=data.title,
                content=data.title,
                group_visibility=data.group_visibility,
                sector_visibility=data.sector_visibility,
                status=PostStatus.VISIBLE,
                post_type=PostType.MEETING,
                meeting=meeting,
            )
        )
        # build_entry rather than log_action: the audit row belongs to the same
        # transaction as the two writes above (log_action commits on its own,
        # which would split one change into two and leave a trail describing
        # data that may not exist).
        db.add(
            build_entry(
                actor=professional,
                action=AuditAction.MEETING_CREATED,
                entity_type="Meeting",
                entity_id=meeting.id,
                details={
                    "title": data.title,
                    "scheduled_at": data.scheduled_at.isoformat(),
                    "group_visibility": data.group_visibility.value,
                    "sector_visibility": data.sector_visibility.value,
                    "calendar_event_id": calendar_event_id,
                },
            )
        )
        db.commit()
    except Exception:
        db.rollback()
        # The event exists at Google and nothing here points at it. Take it
        # back down before reporting the failure, so a retry does not leave a
        # trail of phantom meetings in the professional's calendar.
        google_meet_service.delete_event(db, professional, calendar_event_id)
        logger.exception("Could not record meeting %s after creating it", meeting.id)
        raise HTTPException(
            status_code=500, detail=translate("meetings.creation_failed")
        ) from None

    return (
        db.query(Meeting)
        .options(joinedload(Meeting.creator))
        .filter(Meeting.id == meeting.id)
        .one()
    )


def get_visible_meetings(db: Session, current_user: User) -> list[Meeting]:
    """
    Meetings that have not finished yet and that this user may see.

    Visibility by role, mirroring how the rest of the platform reads content:
      USER          – her own cell, the one the announcement was published to
      PROFESSIONAL  – the meetings she convened
      MODERATOR     – the cells she oversees (moderator_cells)
      ADMIN         – everything

    A meeting already in progress is still listed: the rule is when it ends,
    not when it starts, so a member who is a few minutes late can still find
    her way in from here.

    And only while its announcement is VISIBLE, for every role. The
    announcement is what moderation acts on: a moderator or admin deleting it,
    or two reports hiding it pending review, is a decision that members should
    not see this meeting, and a list that kept publishing the join link would
    quietly undo that decision. Reversible by design — reports dismissed and
    the post back to VISIBLE, and the meeting is listed again. The meeting
    itself is not cancelled: the row and the Google event stay, and cancelling
    a meeting is outside ABF-156.
    """
    now = _utcnow()
    query = (
        db.query(Meeting)
        .options(joinedload(Meeting.creator))
        .join(ForumPost, ForumPost.meeting_id == Meeting.id)
        .filter(
            ForumPost.status == PostStatus.VISIBLE,
            Meeting.scheduled_at >= now - _LOOKBACK,
        )
    )

    if current_user.role == UserRole.ADMIN:
        pass
    elif current_user.role == UserRole.PROFESSIONAL:
        query = query.filter(Meeting.creator_id == current_user.id)
    elif current_user.role == UserRole.MODERATOR:
        cells = [
            and_(
                Meeting.group_visibility == cell["group"],
                Meeting.sector_visibility == cell["sector"],
            )
            for cell in current_user.moderator_cells or []
            if cell.get("group") and cell.get("sector")
        ]
        if not cells:
            return []
        query = query.filter(or_(*cells))
    else:
        # A USER whose cell is not set cannot match any meeting — every
        # meeting carries a concrete group and sector — and asking the
        # database to prove that is pointless work.
        if current_user.user_type is None or current_user.sector is None:
            return []
        query = query.filter(
            Meeting.group_visibility == GroupVisibility(current_user.user_type.value),
            Meeting.sector_visibility == SectorVisibility(current_user.sector.value),
        )

    meetings = query.order_by(Meeting.scheduled_at.asc()).all()
    return [
        meeting
        for meeting in meetings
        if meeting.scheduled_at + timedelta(minutes=meeting.duration_minutes) >= now
    ]
