"""
Meeting service (ABF-156).

The platform's side of a scheduled meeting: who may schedule one and for
which cell, what gets written down when one is scheduled, and which meetings
a given member is allowed to see. Talking to Google is
google_meet_service.py's job — nothing in this file makes an HTTP call.

The split matters at exactly one point: Google is called *before* the
transaction that records what it did, because a change Google refused must
not be written down here as if it had happened. The reverse failure — done at
Google, not recorded here — is recoverable, and each writer recovers from it
in its own way: create_meeting() deletes the event, update_meeting() puts the
old values back, and cancel_meeting() is safe to retry.
"""

import logging
from datetime import UTC, datetime, timedelta

from fastapi import HTTPException
from sqlalchemy import and_, or_
from sqlalchemy.orm import Session, joinedload

from app.core.config import settings
from app.core.constants import (
    AuditAction,
    GroupVisibility,
    PostStatus,
    PostType,
    SectorVisibility,
    UserRole,
)
from app.core.i18n import translate
from app.models.forum import ForumPost
from app.models.meeting import Meeting
from app.models.user import User
from app.schemas.meeting import MeetingCreate, MeetingUpdate
from app.services import google_meet_service
from app.services.audit_service import build_entry

logger = logging.getLogger(__name__)

#: How far back get_visible_meetings() looks before deciding, per row, whether
#: a meeting is over. A prefilter, not the rule: the rule is
#: `scheduled_at + duration_minutes >= now`, and expressing that arithmetic in
#: SQL means writing it twice, once per dialect (SQLite and PostgreSQL date
#: arithmetic do not share a syntax). One day back bounds what the prefilter
#: can return to a handful of rows, which Python then filters exactly.
_LOOKBACK = timedelta(days=1)


def _utcnow() -> datetime:
    """Naive UTC, matching how every timestamp in this project is stored."""
    return datetime.now(UTC).replace(tzinfo=None)


def _may_schedule_for(
    professional: User,
    group_visibility: GroupVisibility,
    sector_visibility: SectorVisibility,
) -> bool:
    """
    Whether this professional's assignment covers the requested cell.

    professional_groups / professional_sectors are the same JSON lists that
    decide which professionals a member sees in the catalogue
    (user_service._visible_to_user()), read here in the other direction: a
    professional may convene the members who can already reach her, and
    nobody else. "all" in a list is the wildcard it is everywhere else.
    """
    groups = professional.professional_groups or []
    sectors = professional.professional_sectors or []
    group_match = "all" in groups or group_visibility.value in groups
    sector_match = "all" in sectors or sector_visibility.value in sectors
    return group_match and sector_match


def create_meeting(db: Session, data: MeetingCreate, professional: User) -> Meeting:
    """
    Schedule a meeting and publish its announcement.

    The caller's role is already PROFESSIONAL — require_role does that — so
    what is left here is the part of "may she do this" that depends on the
    data: is she still an active professional, and is this cell hers.
    """
    if not professional.is_active_professional:
        raise HTTPException(
            status_code=403, detail=translate("meetings.inactive_professional")
        )

    if not _may_schedule_for(
        professional, data.group_visibility, data.sector_visibility
    ):
        raise HTTPException(
            status_code=403, detail=translate("meetings.cell_forbidden")
        )

    duration_minutes = settings.MEETING_DEFAULT_DURATION_MINUTES
    meet_link, calendar_event_id = google_meet_service.create_meeting(
        db,
        professional,
        title=data.title,
        scheduled_at=data.scheduled_at,
        duration_minutes=duration_minutes,
    )

    meeting = Meeting(
        creator_id=professional.id,
        title=data.title,
        scheduled_at=data.scheduled_at,
        duration_minutes=duration_minutes,
        meet_link=meet_link,
        calendar_event_id=calendar_event_id,
        group_visibility=data.group_visibility,
        sector_visibility=data.sector_visibility,
    )

    try:
        db.add(meeting)
        # Flushed, not just added: the id is generated by the model's Python
        # default, which does not run until the INSERT is emitted — and the
        # audit entry below has to name it. Still one transaction; the commit
        # is at the end.
        db.flush()
        # The announcement. Its body is the title: what a member actually
        # reads off this post — when it starts, where to join — travels in
        # structured fields on the meeting, and a sentence assembled here
        # would be a second copy of them that the client cannot format or
        # translate.
        db.add(
            ForumPost(
                author_id=professional.id,
                title=data.title,
                content=data.title,
                group_visibility=data.group_visibility,
                sector_visibility=data.sector_visibility,
                status=PostStatus.VISIBLE,
                post_type=PostType.MEETING,
                meeting=meeting,
            )
        )
        # build_entry rather than log_action: the audit row belongs to the same
        # transaction as the two writes above (log_action commits on its own,
        # which would split one change into two and leave a trail describing
        # data that may not exist).
        db.add(
            build_entry(
                actor=professional,
                action=AuditAction.MEETING_CREATED,
                entity_type="Meeting",
                entity_id=meeting.id,
                details={
                    "title": data.title,
                    "scheduled_at": data.scheduled_at.isoformat(),
                    "group_visibility": data.group_visibility.value,
                    "sector_visibility": data.sector_visibility.value,
                    "calendar_event_id": calendar_event_id,
                },
            )
        )
        db.commit()
    except Exception:
        db.rollback()
        # The event exists at Google and nothing here points at it. Take it
        # back down before reporting the failure, so a retry does not leave a
        # trail of phantom meetings in the professional's calendar.
        google_meet_service.delete_event(db, professional, calendar_event_id)
        logger.exception("Could not record meeting %s after creating it", meeting.id)
        raise HTTPException(
            status_code=500, detail=translate("meetings.creation_failed")
        ) from None

    return (
        db.query(Meeting)
        .options(joinedload(Meeting.creator))
        .filter(Meeting.id == meeting.id)
        .one()
    )


def get_visible_meetings(db: Session, current_user: User) -> list[Meeting]:
    """
    Meetings that have not finished yet and that this user may see.

    Visibility by role, mirroring how the rest of the platform reads content:
      USER          – her own cell, the one the announcement was published to
      PROFESSIONAL  – the meetings she convened
      MODERATOR     – the cells she oversees (moderator_cells)
      ADMIN         – everything

    A meeting already in progress is still listed: the rule is when it ends,
    not when it starts, so a member who is a few minutes late can still find
    her way in from here.

    And only while its announcement is VISIBLE, for every role. The
    announcement is what moderation acts on: a moderator or admin deleting it,
    or two reports hiding it pending review, is a decision that members should
    not see this meeting, and a list that kept publishing the join link would
    quietly undo that decision. Reversible by design — reports dismissed and
    the post back to VISIBLE, and the meeting is listed again. Moderation does
    not cancel the meeting: the row and the Google event stay.

    Nor once its creator has cancelled it (ABF-163), which is not reversible:
    the Google event is gone, so there is nothing left to join. The
    announcement itself stays in the forum and says so — this is a list of
    meetings still ahead, and a cancelled one is not.
    """
    now = _utcnow()
    query = (
        db.query(Meeting)
        .options(joinedload(Meeting.creator))
        .join(ForumPost, ForumPost.meeting_id == Meeting.id)
        .filter(
            ForumPost.status == PostStatus.VISIBLE,
            ForumPost.cancelled_at.is_(None),
            Meeting.scheduled_at >= now - _LOOKBACK,
        )
    )

    if current_user.role == UserRole.ADMIN:
        pass
    elif current_user.role == UserRole.PROFESSIONAL:
        query = query.filter(Meeting.creator_id == current_user.id)
    elif current_user.role == UserRole.MODERATOR:
        cells = [
            and_(
                Meeting.group_visibility == cell["group"],
                Meeting.sector_visibility == cell["sector"],
            )
            for cell in current_user.moderator_cells or []
            if cell.get("group") and cell.get("sector")
        ]
        if not cells:
            return []
        query = query.filter(or_(*cells))
    else:
        # A USER whose cell is not set cannot match any meeting — every
        # meeting carries a concrete group and sector — and asking the
        # database to prove that is pointless work.
        if current_user.user_type is None or current_user.sector is None:
            return []
        query = query.filter(
            Meeting.group_visibility == GroupVisibility(current_user.user_type.value),
            Meeting.sector_visibility == SectorVisibility(current_user.sector.value),
        )

    meetings = query.order_by(Meeting.scheduled_at.asc()).all()
    return [meeting for meeting in meetings if _ends_at(meeting) >= now]


def _ends_at(meeting: Meeting) -> datetime:
    """When a meeting is over: its start plus the duration it was booked for."""
    return meeting.scheduled_at + timedelta(minutes=meeting.duration_minutes)


def _load(db: Session, meeting_id: str) -> Meeting:
    """The meeting as MeetingResponse reads it, creator included."""
    return (
        db.query(Meeting)
        .options(joinedload(Meeting.creator))
        .filter(Meeting.id == meeting_id)
        .one()
    )


def _lock_own_meeting(
    db: Session, meeting_id: str, professional: User
) -> tuple[Meeting, ForumPost]:
    """
    The meeting and its announcement, locked, once she is shown to own it.

    404 for an id that does not exist, then 403 for a meeting someone else
    created — the order forum_service.update_post() uses. Every other role is
    already a 403 by then: the endpoints require PROFESSIONAL.

    Both rows are locked (FOR UPDATE; a no-op on SQLite) until the request
    commits, and that includes the call to Google. Two tabs editing the same
    meeting must not reach Google in one order and the database in the other,
    which would leave the calendar saying one thing and the forum another.
    The price is a lock held across one HTTP call, bounded by
    GOOGLE_CALENDAR_TIMEOUT_SECONDS, on rows that only their creator writes.
    `of=` keeps each lock on its own table, as in forum_service.delete_post().
    """
    meeting = (
        db.query(Meeting)
        .filter(Meeting.id == meeting_id)
        .with_for_update(of=Meeting)
        .first()
    )
    if meeting is None:
        raise HTTPException(status_code=404, detail=translate("meetings.not_found"))
    if meeting.creator_id != professional.id:
        raise HTTPException(status_code=403, detail=translate("meetings.creator_only"))

    # Exactly one announcement per meeting — create_meeting() writes the two
    # in one transaction — so .one() is an assertion, not a lookup that may
    # come back empty.
    announcement = (
        db.query(ForumPost)
        .filter(ForumPost.meeting_id == meeting.id)
        .with_for_update(of=ForumPost)
        .one()
    )
    return meeting, announcement


def update_meeting(
    db: Session, meeting_id: str, data: MeetingUpdate, professional: User
) -> Meeting:
    """
    Change a meeting's title, its time, or both, everywhere it is written.

    Three copies of the same facts move together: the Meeting row, its
    announcement (whose title and body are the meeting's title — see
    create_meeting()), and the event in her Google Calendar. The Meet link
    does not change, so a member who already copied it still gets in.

    Refused with a 409 once the meeting is cancelled (its event is gone, so
    there is nothing at Google to edit) or over (an edit would rewrite what
    the cell was told about a meeting that already happened). A request that
    changes nothing — the same title, the same instant — returns the meeting
    as it is, without calling Google or writing an audit entry for an edit
    that did not happen.

    Moderation is not consulted: an announcement a moderator hid can still be
    corrected by its author, and stays hidden.
    """
    if not professional.is_active_professional:
        # The same rule as create_meeting(): an admin who deactivated her has
        # stopped her scheduling, and moving a meeting is scheduling it again.
        raise HTTPException(
            status_code=403, detail=translate("meetings.inactive_professional_edit")
        )

    meeting, announcement = _lock_own_meeting(db, meeting_id, professional)

    if announcement.cancelled_at is not None:
        raise HTTPException(
            status_code=409, detail=translate("meetings.already_cancelled")
        )
    if _ends_at(meeting) <= _utcnow():
        raise HTTPException(status_code=409, detail=translate("meetings.already_ended"))

    # The schema guarantees that every field present is a real value, so None
    # here means "left out" and the stored value stands.
    title = data.title if data.title is not None else meeting.title
    scheduled_at = (
        data.scheduled_at if data.scheduled_at is not None else meeting.scheduled_at
    )

    changes: dict[str, dict[str, str]] = {}
    if title != meeting.title:
        changes["title"] = {"from": meeting.title, "to": title}
    if scheduled_at != meeting.scheduled_at:
        changes["scheduled_at"] = {
            "from": meeting.scheduled_at.isoformat(),
            "to": scheduled_at.isoformat(),
        }
    if not changes:
        return _load(db, meeting.id)

    # Read before anything can expire them: the rollback below expires every
    # attribute on the session, and these are what puts the event back.
    previous_title = meeting.title
    previous_scheduled_at = meeting.scheduled_at
    event_id = meeting.calendar_event_id
    duration_minutes = meeting.duration_minutes

    google_meet_service.update_event(
        db,
        professional,
        event_id,
        title=title,
        scheduled_at=scheduled_at,
        duration_minutes=duration_minutes,
    )

    try:
        meeting.title = title
        meeting.scheduled_at = scheduled_at
        announcement.title = title
        announcement.content = title
        # build_entry rather than log_action, as in create_meeting(): the
        # audit row commits with the change it describes, or not at all.
        db.add(
            build_entry(
                actor=professional,
                action=AuditAction.MEETING_UPDATED,
                entity_type="Meeting",
                entity_id=meeting.id,
                details={"changes": changes, "calendar_event_id": event_id},
            )
        )
        db.commit()
    except Exception:
        db.rollback()
        # Google already shows the new values and nothing here does. Put the
        # event back the way the forum still describes it, so the two agree
        # on the old meeting rather than disagree about the new one.
        try:
            google_meet_service.update_event(
                db,
                professional,
                event_id,
                title=previous_title,
                scheduled_at=previous_scheduled_at,
                duration_minutes=duration_minutes,
            )
        except Exception:
            logger.exception("Could not restore calendar event %s", event_id)
        logger.exception("Could not record the edit of meeting %s", meeting_id)
        raise HTTPException(
            status_code=500, detail=translate("meetings.update_failed")
        ) from None

    return _load(db, meeting_id)


def cancel_meeting(db: Session, meeting_id: str, professional: User) -> None:
    """
    Call a meeting off: delete its Google event, mark its announcement.

    The announcement is marked, not deleted. It stays in the cell's forum
    reading "cancelled", without a way in, so a member who planned to come
    finds out where she would have looked — deleting it would make the
    meeting quietly vanish. The Meeting row stays too: what was scheduled,
    and the audit entry naming it, are the only record left once the Google
    event is gone.

    The event is deleted first, and the announcement marked only once Google
    agrees, so "cancelled" is never shown for a meeting that is still in her
    calendar. If the write then fails, the event is gone and the meeting is
    not yet marked — and pressing cancel again completes it, because
    cancel_event() counts an event that is already gone as deleted.

    Idempotent: cancelling a cancelled meeting does nothing and succeeds, like
    forum_service.delete_post() on a deleted post — a second press, or the
    retry above racing a first that did land, is not an error.

    A meeting that is already over cannot be cancelled: it took place, and
    "cancelled" would rewrite what the cell saw. That 409 is decided by
    Google, not by the clock alone, because an unmarked meeting past its end
    is also what the failed write above leaves behind when the retry comes
    late. Its event tells the two apart — still in her calendar, the meeting
    happened; gone, an earlier cancellation already deleted it, and this one
    only has to record that. Without the lookup that retry would be refused
    for good, and the cell would be left with an announcement that never
    says the meeting was called off.

    Unlike update_meeting(), a deactivated professional may still cancel. A
    meeting she can no longer run is exactly the one that should be called
    off, and refusing her would leave the cell a live join button for it.
    """
    meeting, announcement = _lock_own_meeting(db, meeting_id, professional)

    if announcement.cancelled_at is not None:
        return
    if _ends_at(meeting) > _utcnow():
        google_meet_service.cancel_event(db, professional, meeting.calendar_event_id)
    elif not google_meet_service.event_is_gone(
        db, professional, meeting.calendar_event_id
    ):
        # Over, and its event untouched: it took place. Only looked up, never
        # deleted — a past meeting stays in her calendar as the record of it.
        raise HTTPException(status_code=409, detail=translate("meetings.already_ended"))

    try:
        announcement.cancelled_at = _utcnow()
        db.add(
            build_entry(
                actor=professional,
                action=AuditAction.MEETING_CANCELLED,
                entity_type="Meeting",
                entity_id=meeting.id,
                details={
                    "title": meeting.title,
                    "scheduled_at": meeting.scheduled_at.isoformat(),
                    "calendar_event_id": meeting.calendar_event_id,
                    "forum_post_id": announcement.id,
                },
            )
        )
        db.commit()
    except Exception:
        db.rollback()
        logger.exception("Could not record the cancellation of meeting %s", meeting_id)
        raise HTTPException(
            status_code=500, detail=translate("meetings.cancellation_failed")
        ) from None
