"""add sla_escalation_sent_at to users

Revision ID: 9dd5b3c88c0d
Revises: 91c4a53eec32
Create Date: 2026-07-16 17:22:52.131328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd5b3c88c0d'
down_revision: Union[str, Sequence[str], None] = '91c4a53eec32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sla_escalation_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sla_escalation_sent_at')
    # ### end Alembic commands ###
